# Generated by Django 6.0.3 on 2026-03-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фото категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО заказчика')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('card_text', models.TextField(blank=True, verbose_name='Текст открытки')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('transfer', 'Переводом')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('assembling', 'В сборке'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('composition', models.TextField(blank=True, verbose_name='Состав букета')),
                ('size', models.CharField(choices=[('small', 'Малый'), ('medium', 'Средний'), ('large', 'Большой')], default='medium', max_length=20, verbose_name='Размер')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('march8', '8 марта'), ('anniversary', 'Годовщина'), ('love', 'Любовь'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Повод')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('pre_order', 'Под заказ')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
